name: hawalnir1
description: A Kurdish News gathering.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: 

dependencies:
  flutter_offline: 
  cached_network_image: 
  json_annotation: 
  sqflite: 
  path_provider: 
  http: 
  transparent_image: 
  #flutter_html_view: "^0.5.8"
  flutter_html: 
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # - images/a_dot_burr.jpeg
    - assets/images/placeholder.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: lib/src/fonts/NotoKufiArabic-Regular.ttf
    - family: NotoSansArabic
      fonts:
        - asset: lib/src/fonts/NotoSansArabic-Regular.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
